<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-5QUMFMFQ" failures="0" tests="4" name="com.selenium.Projecr2.NewTest" time="1.209" errors="1" timestamp="2023-12-01T05:23:16 GMT-08:00" skipped="1">
  <testcase classname="com.selenium.Projecr2.NewTest" name="test1" time="0.169"/>
  <system-out/>
  <testcase classname="com.selenium.Projecr2.NewTest" name="test2" time="0.014"/>
  <system-out/>
  <testcase classname="com.selenium.Projecr2.NewTest" name="test3" time="1.025">
    <error message="Method com.selenium.Projecr2.NewTest.test3() didn&#039;t finish within the time-out 1000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.selenium.Projecr2.NewTest.test3() didn't finish within the time-out 1000
at java.base@17.0.8.1/java.lang.Thread.sleep(Native Method)
at app//com.selenium.Projecr2.NewTest.test3(NewTest.java:23)
at java.base@17.0.8.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base@17.0.8.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base@17.0.8.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base@17.0.8.1/java.lang.reflect.Method.invoke(Method.java:568)
at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at app//org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base@17.0.8.1/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@17.0.8.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@17.0.8.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@17.0.8.1/java.lang.Thread.run(Thread.java:833)
]]>
    </error>
  </testcase> <!-- test3 -->
  <system-out/>
  <testcase classname="com.selenium.Projecr2.NewTest" name="test4" time="0.001">
    <skipped/>
  </testcase> <!-- test4 -->
  <system-out/>
</testsuite> <!-- com.selenium.Projecr2.NewTest -->
